### ISSUE TITLE
Provide wheel for python 3.9

### ISSUE THREAD

**Issue by ldorigo** [explosion/cymem#31]
Hello, I can't get cymem to install with python 3.9 - there's no wheel, and building from source is failing. Would it be possible to provide a wheel for python 3.9?

**Comment by adrianeboyd** [comment]
There are python 3.9 wheels for v2.0.5 for x86_64 and this package is pretty straightforward to compile from source (only requires cython), so I'm not sure what might be going on. Do you have more details about the pip/install errors on your end?

**Comment by adrianeboyd** [comment]
Ah, possibly you just need to upgrade `pip` and `setuptools`? Try that if you haven't.
