### ISSUE TITLE
travis icon in readme broken

### ISSUE THREAD

**Issue by esc** [explosion/cymem#6]
It points to:

https://travis-ci.org/spacy-io/cymem

but there is no build at this url. I looked at the builds for all spacy-io projects on travis but couldn't find cymem. If you tell me where it is now, I'll make a pull-request.

**Comment by honnibal** [comment]
Ah. Travis isn't so smart about redirects. The new org name is explosion.

**Comment by esc** [comment]
kay, I seen you fixed it already.
